
service: apicategorias

frameworkVersion: '2'

package:
  include:
    - node_modules/
provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:  #estas 2 lineas hacen que se cambie el order del nombre del api getway
    shouldStartNameWithService: true
  lambdaHashingVersion: 20201221
  region: us-east-1
  profile: apicategorias

custom:
  arnCognito: arn:aws:cognito-idp:us-east-1:525713275182:userpool/us-east-1_urWAO6CX4
functions:
  app:
    handler: handler.Server
    
    events:
      - http:
          path: /user
          method: get
          authorizer:
              arn: ${self:custom.arnCognito}

      - http: 
          path: /user
          method: post
      - http:
          path: /user/signup
          method: post
      - http:
          path: /user/login
          method: post
      - http:
          path: /user/mailprueba
          method: post
      - http:
            path: /user/listobjects
            method: get
      - http:
            path: /user/uploadimg
            method: post
      - http:
          path: /document/upload
          method: post
      - http:
          path: /api/document/getUrlPreload
          method: post
          cors:
            origin: '*'
          authorizer:
            arn: ${self:custom.arnCognito} 
  hello:
    handler: handler.hello
    events:
      - http:
          path: /traer
          method: get
  

plugins:
  - serverless-offline